### PR TITLE
Fix bugs found in PED - General and Find command

### LINKED ISSUE #135: [PE-D] Unable to handle invalid local data file initialization
The SUT should be able to handle invalid local data files, with error messages or launch with sample data.

Reproduce steps:

1. Open `data/foodinventory.json`

1. Change some data to invalid value, like:

1. Launch the app and the app is blank without error message or does not start with sample data.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: zhXchD/ped#1

### LINKED ISSUE #138: [PE-D] Dismatch error message for extra parameters
When extra parameters are parsed, the SUT will try to treat it as part of the previous parameter instead of identifying it as a mis-typed parameter prefix.

Reproduce steps:
1. Type command `add d/extra parameter q/1 e/01-02-2000 o/what is this`
1. The SUT treats ` o/what is this` as part of the expiry date instead of identidying that the user uses extra illegal parameters.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: zhXchD/ped#4

### LINKED ISSUE #144: [PE-D] Wrong command in examples of "Deleting a food item"
`find tuna` here should be `find d/tuna`

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: T-Fang/ped#3

### LINKED ISSUE #150: [PE-D] Unable to handle error for multiple identical prefixes
According to the user guide, the add command format is as follows

Since DESCRIPTION does not have a `...` attached to the end of it, this means that by right, the system should only accept command inputs with only 1 description. If a user uses more than 1 prefixes of `d/` in his/her command, an error should be thrown to remind the user to only input 1 description for the item.

However, in my testing, I tried to enter a food item with 2 descriptions and no error message was found.

Command input: add d/Pork d/Mee Pok e/01-01-2021 q/1.5 can p/low

Output:

The system erreneously accepts my input and assigns the description as “Mee Pok”, when the system should have detected multiple prefixes of “d/” and throw an error to remind me to only enter 1 prefix of “d/”

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: iamjamestan/ped#4

### LINKED ISSUE #157: [PE-D] Maintain consistency between application and UG
The format of the commands presented by the application and the User Guide are different from each other. Furthermore, the format on the application lacks information, mainly on which parameters are optional and which are not.

_Add Command on SimplyKitchen application_

_Format as seen on User Guide_

As seen from above, the format presented in the application leaves out critical information which may impede the user's experience.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: siangernlow/ped#5

### LINKED ISSUE #159: [PE-D] Outdated Diagram
Under `Searching for a food item`, the diagram shown is presumably outdated from the current version of the application. It should be up to date to not confuse readers.

-------------
Labels: `severity.High` `type.DocumentationBug`
original: siangernlow/ped#7

### LINKED ISSUE #160: [PE-D] Error message of application
When deleting an item, different error messages are shown for negative indexes and indexes that are valid but not in range. However, is there a reason in a distinct difference between the two or can the usage message be shown for both errors?

_Valid but out of range_

_Negative, but still a number_

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: siangernlow/ped#8

### LINKED ISSUE #161: [PE-D] Duplicate parameters
When a compulsory parameter is duplicated in the command input, the most recent one is taken. This should be highlighted inside the UG.

_12-12-20 would be taken as the date instead of 11-10-2020_

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: siangernlow/ped#9

### LINKED ISSUE #168: [PE-D] Using find with 2 of the same parameters only returns the last one
For example `find d/apple d/cake` will effectively only run `find d/cake`

*after running the above command*

Expected result:

Both apple and cake will be listed.

How to recreate:
1. reset the data to the default (delete the .json data file)
2. run `find d/apple d/cake`. Observe the result is the second pic above.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: JoeyChenSmart/ped#3

### LINKED ISSUE #175: Expired window has no placeholder text when no items are listed

### PR DESCRIPTION
**Pull request by jonahtanjz**
- Fix issues found under general and find command

### CODE REVIEW

File: src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -20,9 +20,9 @@
 
     public static final String MESSAGE_USAGE = "Usage: " + COMMAND_WORD + " "
             + PREFIX_DESCRIPTION + "DESCRIPTION "
-            + PREFIX_PRIORITY + "PRIORITY "
             + PREFIX_EXPIRY_DATE + "EXPIRY DATE "
             + PREFIX_QUANTITY + "QUANTITY "
+            + "[" + PREFIX_PRIORITY + "PRIORITY] "
```
Comment (bchenghi) [inline src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java:25]: The PED bug #157 stated that the tester was unsure which fields were optional and which were not. Do you think we should explain that here as well? Perhaps in the next line, "Fields in square brackets are optional"? Similarly for EditCommand and FindCommand.

File: src/main/java/seedu/simplykitchen/MainApp.java [hunk 2]
```diff
@@ -90,6 +90,7 @@ private Model initModelManager(Storage storage, ReadOnlyUserPrefs userPrefs) {
             logger.warning("Data file not in the correct format. "
                     + "Will be starting with an empty FoodInventory");
             initialData = new FoodInventory();
+            return new ModelManager(initialData, userPrefs, true);
```
Comment (rolandyuwy) [inline src/main/java/seedu/simplykitchen/MainApp.java:93]: This looks good. I suggest we standardise the result display message for all errors caught in this code. Will open a new issue on this.

File: src/main/java/seedu/simplykitchen/logic/parser/EditCommandParser.java [hunk 3]
```diff
@@ -86,4 +93,15 @@ public EditCommand parse(String args) throws ParseException {
         return Optional.of(ParserUtil.parseTags(tagSet));
     }
 
+    /**
+     * Generate the error message for the invalid index number.
+     */
+    private String generateParseExceptionMessage(String args) {
+        if (isNonPositiveUnsignedDouble(args.trim()) || isIntegerOverflow(args.trim())) {
+            return MESSAGE_INVALID_FOOD_DISPLAYED_INDEX;
```
Comment (rolandyuwy) [inline src/main/java/seedu/simplykitchen/logic/parser/EditCommandParser.java:101]: To standardise, we need to remember to implement this for Changeqty command too.

File: src/main/java/seedu/simplykitchen/commons/util/StringUtil.java [hunk 4]
```diff
@@ -85,4 +85,38 @@ public static boolean isNonZeroSignedDouble(String s) {
...
+            return false;
+        }
+    }
+
+    /**
+     * Returns true if {@code s} represents a integer more than {@code Integer.MAX_VALUE} <br>
+     * or less than {@code Integer.MIN_VALUE}
+     * @throws NullPointerException if {@code s} is null.
+     */
+    public static boolean isIntegerOverflow(String s) {
```
Comment (rolandyuwy) [inline src/main/java/seedu/simplykitchen/commons/util/StringUtil.java:112]: Good catch

**Review by rolandyuwy — APPROVED** [review]
No issues with changes, LGTM

**Review by bchenghi — COMMENTED** [review]
LGTM! I added one comment.

File: src/main/java/seedu/simplykitchen/MainApp.java (hunk 2 above)
Comment (jonahtanjz) [reply src/main/java/seedu/simplykitchen/MainApp.java:93]: Yup sure.

File: src/main/java/seedu/simplykitchen/logic/parser/EditCommandParser.java (hunk 3 above)
Comment (jonahtanjz) [reply src/main/java/seedu/simplykitchen/logic/parser/EditCommandParser.java:101]: Alright.

File: src/main/java/seedu/simplykitchen/commons/util/StringUtil.java (hunk 4 above)
Comment (jonahtanjz) [reply src/main/java/seedu/simplykitchen/commons/util/StringUtil.java:112]: Thanks

File: src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java (hunk 1 above)
Comment (jonahtanjz) [reply src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java:25]: Hmm I'm not sure about this but I guess it's fine because it's stated in the user guide and this would make the error message very long?

Comment (bchenghi) [reply src/main/java/seedu/simplykitchen/logic/commands/AddCommand.java:25]: OK agreed.
